openapi: 3.0.0
info:
  title: Payment Provider
  version: '1.0'
  description: Interface that models the operations available for the Payment Provider that supports payments by customers in ACMESky.
servers:
  - url: 'http://localhost:3000'
paths:
  /payments/request:
    parameters: []
    post:
      summary: createPaymentRequest
      operationId: createPaymentRequest
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
      description: |-
        Creates a payment request for a user.
        API for: ACMESky
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
        description: ''
  /payments/pay:
    parameters: []
    post:
      summary: sendPayment
      operationId: sendPayment
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      description: |-
        Sends the payment data for paying a request.
        API for: User
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentData'
        description: ''
components:
  schemas:
    PaymentRequest:
      title: PaymentRequest
      type: object
      properties:
        amount:
          type: number
          format: double
          minimum: 0
        description:
          type: string
        payment_receiver:
          type: string
        transaction_id:
          type: string
          format: uuid
      required:
        - amount
        - description
        - payment_receiver
        - transaction_id
    PaymentData:
      title: PaymentData
      type: object
      properties:
        transaction_id:
          type: string
          format: uuid
        credit_cart_number:
          type: string
          pattern: '[0-9]{16,16}'
        cvv:
          type: string
          pattern: '[0-9]{3,3}'
        expiration_date:
          type: string
          format: date
        owner_name:
          type: string
      required:
        - transaction_id
        - credit_cart_number
        - cvv
        - expiration_date
        - owner_name
    Error:
      title: Error
      type: object
      properties:
        description:
          type: string
          minLength: 1
      required:
        - description
