openapi: 3.0.0
info:
  title: ProntoGram
  version: '1.0'
  description: Interface that models the operations available for ProntoGram in ACMESky.
servers:
  - url: 'http://localhost:3000'
paths:
  /messages:
    post:
      summary: sendMessage
      operationId: sendMessage
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      description: |-
        Sends the message to ProntoGram for being dispatched to the actual user.
        API for: ACMESky
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
components:
  schemas:
    Message:
      title: Message
      type: object
      properties:
        sender:
          type: string
          minLength: 1
        receiver:
          type: string
          minLength: 1
        body:
          type: string
          minLength: 1
      required:
        - sender
        - receiver
        - body
    Error:
      title: Error
      type: object
      properties:
        description:
          type: string
          minLength: 1
      required:
        - description
