site_name: ACMESky - Documentazione progetto | SOSENG
site_author: Marco Ferrati, Tommaso Azzalin
site_description: Documentazione del progetto "ACMESky" del corso di Ingegneria del Software Orientata ai Servizi della LM Informatica presso Università di Bologna, A.A. 2020/2021.
repo_name: sosengers/project-documentation
repo_url: https://github.com/sosengers/project-documentation
copyright: Documentazione del progetto ACMESky realizzato da Marco Ferrati e Tommaso Azzalin, Università di Bologna.
theme:
  name: material
  language: it
  custom_dir: theme
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - navigation.instant
    - search.suggest
  font:
    text: Open Sans
  icon:
    repo: fontawesome/brands/github
  favicon: "assets/favicon.ico"
  logo: "assets/favicon.ico"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Passa a dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Passa a light mode
extra_css:
  - stylesheets/extra.css
edit_uri: ""
plugins:
  - search
  - mermaid2:
      version: 8.8.0
  - with-pdf:
      enabled_if_env: ENABLE_PDF_EXPORT
      author: Marco Ferrati, Tommaso Azzalin
      cover_title: ACMESky
      cover_subtitle: Documentazione del progetto "ACMESky" del corso di Ingegneria del Software Orientata ai Servizi della LM Informatica presso Università di Bologna, A.A. 2020/2021.
      toc_title: Indice
      copyright: Documentazione del progetto "ACMESky"
      output_path: "pdf/AzzalinFerrati-ProjectReport.pdf"
markdown_extensions:
  - abbr
  - admonition
  - footnotes
  - attr_list
  - lightgallery:
      show_description_in_lightgallery: true
      show_description_as_inline_caption: true
      custom_inline_caption_css_class: "text-center text-italic"
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
nav:
  - Home: "index.md"
  - Coreografie: "coreografie.md"
  - Coreografie BPMN: "coreografiebpmn.md"
  - BPMN: "bpmn.md"
  - UML: "uml.md"
  - Servizi web:
    - "": "serviziweb.md"
    - ACMESky: "serviziweb/acmesky.md"
    - Flight Company: "serviziweb/flightcompany.md"
    - Geographical Distances: "serviziweb/geodistances.md"
    - Payment Provider: "serviziweb/paymentprovider.md"
    - ProntoGram: "serviziweb/prontogram.md"
    - Travel Company: "serviziweb/travelcompany.md"
  - Implementazione:
    - "": "implementazione.md"
    - ACMESky: "implementazione/acmesky.md"
    - Flight Company: "implementazione/flightcompany.md"
    - Geographical Distances: "implementazione/geodistances.md"
    - Payment Provider: "implementazione/paymentprovider.md"
    - ProntoGram: "implementazione/prontogram.md"
    - Travel Company: "implementazione/travelcompany.md"
  - Istruzioni per l'esecuzione:
    - "": "executeinstruction.md"
