site_name: ACMESky - Documentazione progetto | SOSENG
site_author: Marco Ferrati, Tommaso Azzalin
site_description: Documentazione del progetto "ACMESky" del corso di Ingegneria del Software Orientata ai Servizi della LM Informatica presso Università di Bologna, A.A. 2020/2021.
repo_name: sosengers/project-documentation
repo_url: https://github.com/sosengers/project-documentation
copyright: Documentazione del progetto ACMESky realizzato da Marco Ferrati e Tommaso Azzalin, Università di Bologna.
theme:
  name: material
  language: it
  custom_dir: theme
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - abbr
  - admonition
  - footnotes
  - attr_list
  - lightgallery
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home: "index.md"
  - Coreografie: "coreografie.md"
  - BPMN: "bpmn.md"
  - UML: "uml.md"
  - Servizi web:
    - "": "serviziweb.md"
    - ACMESky: "serviziweb/acmesky.md"
    - Flight Company: "serviziweb/flightcompany.md"
    - Geographical Distances: "serviziweb/geodistances.md"
    - Payment Provider: "serviziweb/paymentprovider.md"
    - ProntoGram: "serviziweb/prontogram.md"
    - Travel Company: "serviziweb/travelcompany.md"
  - Implementazione:
    - "": "implementazione.md"
    - ACMESky: "implementazione/acmesky.md"
    - Flight Company: "implementazione/flightcompany.md"
    - Geographical Distances: "implementazione/geodistances.md"
    - Payment Provider: "implementazione/paymentprovider.md"
    - ProntoGram: "implementazione/prontogram.md"
    - Travel Company: "implementazione/travelcompany.md"
