site_name: ACMESky - Documentazione progetto | SOSENG
site_author: Marco Ferrati, Tommaso Azzalin
site_description: Documentazione del progetto "ACMESky" del corso di Ingegneria del Software Orientata ai Servizi della LM Informatica presso Università di Bologna, A.A. 2020/2021.
repo_name: sosengers/project-documentation
repo_url: https://github.com/sosengers/project-documentation
copyright: Documentazione del progetto ACMESky realizzato da Marco Ferrati e Tommaso Azzalin, Università di Bologna.
theme:
  name: material
  language: it
  custom_dir: theme
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
markdown_extensions:
  - abbr
  - admonition
  - footnotes
  - attr_list
  - lightgallery
nav:
  - Home: "index.md"
  - Coreografie: "coreografie.md"
  - BPMN: "bpmn.md"
  - UML: "uml.md"
  - Servizi web:
    - "": "serviziweb.md"
    - ACMESky: "serviziweb/acmesky/index.md"
    - Flight Company: "serviziweb/flightcompany/index.md"
    - Geographical Distances: "serviziweb/geodistances/index.md"
    - Payment Provider: "serviziweb/paymentprovider/index.md"
    - ProntoGram: "serviziweb/prontogram/index.md"
    - Travel Company: "serviziweb/travelcompany/index.md"
  - Implementazione: "implementazione.md"
