site_name: ACMESky - Documentazione progetto | SOSENG
site_author: Marco Ferrati, Tommaso Azzalin
site_description: Documentazione del progetto "ACMESky" del corso di Ingegneria del Software Orientata ai Servizi della LM Informatica presso Università di Bologna, A.A. 2020/2021.
repo_name: sosengers/project-documentation
repo_url: https://github.com/sosengers/project-documentation
theme:
  name: material
  language: it
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - toc.integrate
markdown_extensions:
  - abbr
  - admonition
  - footnotes
  - attr_list
nav:
  - Home: "index.md"
  - Coreografie: "coreografie.md"
  - BPMN: "bpmn.md"
  - UML: "uml.md"
  - Implementazione: "implementazione.md"
