name: ci
on:
  push:
    branches:
      - main
jobs:
  site-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force --clean --config-file ./mkdocs.ymld
  pdf-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: pip install -r requirements.txt
      - run: mkdir converted_mermaid_diagrams
      - run: sudo apt install pandoc
      - run: sudo npm install -g mermaid.cli --allow-root --unsafe-perm=true
      - run: sudo rm /usr/bin/chromium-browser
      - run: markdown_mermaid_to_images -f docs/implementazione -o converted_mermaid_diagrams
      - run: cp converted_mermaid_diagrams/* docs/implementazione/
      - run: ENABLE_PDF_EXPORT=1 mkdocs build
      - uses: actions/upload-artifact@v2
        with:
          name: AzzalinFerrati-ProjectReport
          path: site/pdf/AzzalinFerrati-ProjectReport.pdf